import { v4 as uuidv4 } from "uuid";

export const guestNames = [
  "Emma Anderson",
  "Liam Johnson",
  "Olivia Thompson",
  "Noah Davis",
  "Ava Martinez",
  "Isabella Garcia",
  "Sophia Smith",
  "Mia Wilson",
  "Charlotte Taylor",
  "Amelia Anderson",
  "Harper Thomas",
  "Ethan Robinson",
  "Alexander Clark",
  "James Lewis",
  "Benjamin Walker",
  "Elijah Hall",
  "William Lewis",
  "Michael Young",
  "Oliver Scott",
  "Daniel Green",
  "Matthew Evans",
  "Joseph Turner",
  "Samuel Hernandez",
  "David Phillips",
  "Henry Martinez",
  "Emma Davis",
  "Emily Rodriguez",
  "Madison Martin",
  "Elizabeth Garcia",
  "Evelyn Williams",
  "Victoria Moore",
  "Sofia Rodriguez",
  "Scarlett Martinez",
  "Grace Clark",
  "Chloe White",
  "Penelope Wilson",
  "Layla Harris",
  "Riley Turner",
  "Zoey Hernandez",
  "Eleanor Scott",
  "Nathan Johnson",
  "Benjamin Davis",
  "Daniel Lee",
  "Jackson Hall",
  "Matthew Young",
  "Sebastian Brown",
  "Jack Adams",
  "Samuel Martinez",
  "Joseph Robinson",
  "Andrew Allen",
  "Lucas Thomas",
  "David Turner",
  "Henry Roberts",
  "William Rodriguez",
  "Michael Clark",
  "Joseph Wilson",
  "Benjamin Moore",
  "Alexander Mitchell",
  "David Harris",
  "Ethan Martinez",
  "Alexander Davis",
  "William Walker",
  "Daniel Anderson",
  "Matthew Turner",
  "David Hernandez",
  "Benjamin Johnson",
  "Samuel Davis",
  "Alexander Taylor",
  "Daniel White",
  "Ethan Thompson",
  "Alexander Harris",
  "William Wilson",
  "Samuel Clark",
  "Benjamin Turner",
  "Joseph Smith",
  "David Adams",
  "Michael Davis",
  "Matthew Robinson",
  "William Martin",
  "Daniel Lewis",
  "Samuel Martinez",
  "David Turner",
  "Alexander Harris",
  "Benjamin Johnson",
  "Ethan Davis",
  "Alexander Taylor",
  "Samuel Turner",
  "David Hernandez",
  "William White",
  "Benjamin Thompson",
  "Joseph Walker",
  "Michael Adams",
  "Matthew Davis",
  "Daniel Clark",
  "Samuel Smith",
  "David Lewis",
  "Benjamin Wilson",
  "Ethan Robinson",
  "Alexander Hall",
  "William Roberts",
];

export const getRandomGuestName = () => {
  const randomIndex = Math.floor(Math.random() * guestNames.length);
  const name = guestNames[randomIndex];
  return `${name} (Guest)`;
};

export const generateGuid = () => {
  return uuidv4();
};
